// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddProxy(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AddRule(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function ClearCache():Promise<void>;

export function DeleteProxy(arg1:number):Promise<void>;

export function DeleteRule(arg1:number):Promise<void>;

export function ExportRules():Promise<string>;

export function GetBudgetStatus():Promise<database.BudgetStatus>;

export function GetCACertPath():Promise<string>;

export function GetCacheStats():Promise<database.CacheStats>;

export function GetCostSummary():Promise<database.CostSummary>;

export function GetOutputProxies():Promise<Array<database.OutputProxy>>;

export function GetProxies():Promise<Array<database.Proxy>>;

export function GetProxyStatus():Promise<database.ProxyStatus>;

export function GetRealtimeStats():Promise<database.RealtimeStats>;

export function GetRules():Promise<Array<database.Rule>>;

export function GetSettings():Promise<Record<string, string>>;

export function ImportProxies(arg1:string):Promise<number>;

export function ImportRules(arg1:string):Promise<number>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function TestRule(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleRule(arg1:number,arg2:boolean):Promise<void>;

export function UpdateRuleById(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:boolean):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string):Promise<void>;
