// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddProxy'](arg1, arg2, arg3, arg4, arg5);
}

export function AddRule(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddRule'](arg1, arg2, arg3, arg4);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function DeleteProxy(arg1) {
  return window['go']['main']['App']['DeleteProxy'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function ExportRules() {
  return window['go']['main']['App']['ExportRules']();
}

export function GetBudgetStatus() {
  return window['go']['main']['App']['GetBudgetStatus']();
}

export function GetCACertPath() {
  return window['go']['main']['App']['GetCACertPath']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetCostSummary() {
  return window['go']['main']['App']['GetCostSummary']();
}

export function GetOutputProxies() {
  return window['go']['main']['App']['GetOutputProxies']();
}

export function GetProxies() {
  return window['go']['main']['App']['GetProxies']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRealtimeStats() {
  return window['go']['main']['App']['GetRealtimeStats']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportProxies(arg1) {
  return window['go']['main']['App']['ImportProxies'](arg1);
}

export function ImportRules(arg1) {
  return window['go']['main']['App']['ImportRules'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestRule'](arg1, arg2, arg3);
}

export function ToggleRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleRule'](arg1, arg2);
}

export function UpdateRuleById(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateRuleById'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}
